### ============================================================================
### This files takes the data from data folder on the anderson and cuddy 
### examples and makes tables from them. These tables are tables 4 and 5 in 
### the paper.
### ============================================================================

#' Make pretty strings.
#' @param x Numeric matrix.
#' @param digits Digits to prettify with.

pretty = function(x, digits = 2, nsmall = 2) {
  y = sapply(x, function(x) format(signif(round(x, digits = digits), digits),
                                   nsmall = nsmall))
  dim(y) = dim(x)
  y
}

#' Make parentheses for means and sds. 
#' 
#' 
#' @param means Vector of means.
#' @param sds Vector of standard deviations.
#' @value A vector of "mean (sd)".
#' @source https://stat.ethz.ch/pipermail/r-help/2011-July/284323.html

msd = function(means, sds) {
  stopifnot(dim(means) == dim(sds))
  y = paste(means, " (", sds, ")", sep = "") 
  dim(y) = dim(means)
  y
} 

#' Get means and sds from a list of ma objects.
#' @param ma A list of ma objects.
#' @return A matrix of means or sds.
get_means = function(ma) {
  
  theta0_ma_mean = c(publipha::extract_theta0(ma$cma),
                     publipha::extract_theta0(ma$phma),
                     publipha::extract_theta0(ma$psma))
  
  tau_ma_mean = c(publipha::extract_tau(ma$cma),
                  publipha::extract_tau(ma$phma),
                  publipha::extract_tau(ma$psma))
  
  eta_ma_mean = rbind(c(NaN, NaN),
                     publipha::extract_eta(ma$phma)[1:2],
                     publipha::extract_eta(ma$psma)[2:3])
  
  cbind(theta0_ma_mean, tau_ma_mean, eta_ma_mean)
  
}

get_sds = function(ma) {
  
  theta0_ma_sd = c(publipha::extract_theta0(ma$cma, sd),
                     publipha::extract_theta0(ma$phma, sd),
                     publipha::extract_theta0(ma$psma, sd))
  
  tau_ma_sd = c(publipha::extract_tau(ma$cma, sd),
                  publipha::extract_tau(ma$phma, sd),
                  publipha::extract_tau(ma$psma, sd))
  
  eta_ma_sd = rbind(c(NaN, NaN),
                      publipha::extract_eta(ma$phma, sd)[1:2],
                      publipha::extract_eta(ma$psma, sd)[2:3])
  
  cbind(theta0_ma_sd, tau_ma_sd, eta_ma_sd)
  
}


tables_anderson = list(
msd(cbind(pretty(loo_anderson_all_means, nsmall = 0), 
          pretty(get_means(ma_anderson_all))), 
    cbind(pretty(loo_anderson_all_sds, nsmall = 0), 
          pretty(get_sds(ma_anderson_all)))),

msd(cbind(pretty(loo_anderson_best_means, nsmall = 0), 
          pretty(get_means(ma_anderson_best))), 
    cbind(pretty(loo_anderson_best_sds, nsmall = 0), 
          pretty(get_sds(ma_anderson_best)))),

msd(cbind(pretty(loo_anderson_worst_means, nsmall = 0), 
          pretty(get_means(ma_anderson_worst))), 
    cbind(pretty(loo_anderson_worst_sds, nsmall = 0), 
          pretty(get_sds(ma_anderson_worst)))))




tables_cuddy = list(msd(cbind(pretty(loo_cuddy_means, nsmall = 0), 
          pretty(get_means(ma_cuddy2018))), 
    cbind(pretty(loo_cuddy_sds, nsmall = 0), 
          pretty(get_sds(ma_cuddy2018)))),

msd(cbind(pretty(loo_no_means, nsmall = 0), 
          pretty(get_means(ma_cuddy2018_no))), 
    cbind(pretty(loo_no_sds, nsmall = 0), 
          pretty(get_sds(ma_cuddy2018_no)))))

add_names = function(tab) {
  rownames(tab) = c("uncorrected", 
                    "\\emph{p}-hacking", 
                    "publication bias")
  
  colnames(tab) = c("LOOIC",
                    "\\multicolumn{1}{c}{$\\theta_{0}$}",
                    "\\multicolumn{1}{c}{$\\tau$}",
                    "\\multicolumn{1}{c}{$\\pi_{1}/\\rho_{1}$}",
                    "\\multicolumn{1}{c}{$\\pi_{2}/\\rho_{2}$}")
  tab
}

one_table = function(tab) {
  tab = xtable::xtable(add_names(tab))
  xtable::align(tab) = c("l", rep("r", 5))
  tab = print(tab, sanitize.rownames.function = identity,
              sanitize.colnames.function = identity,
              hline.after = c(0, 3), print.results = FALSE)
  tab = readLines(textConnection(tab))[6:11]
  tab = gsub("(NaN)", "", tab, fixed = TRUE)
  gsub("NaN", "", tab, fixed = TRUE)
}


### ============================================================================
### Now we make the numbers into tables.
### ============================================================================

anderson_table = 
  c("%% This document is generated by R: DO NOT EDIT BY HAND!",
    "\\begin{table}",
    "\\noindent",
    "\\caption{\\label{tab:Anderson2010}Violent video games example: Posterior means for LOOICs and parameters (mean effect $\\theta$, standard deviation $\\tau$, probabilities of \\emph{p}-hacking $\\pi$/probabilities of being published $\\rho$) of the \\emph{p}-hacking, publication bias, and classical meta-analysis (uncorrected) model estimated on the aggressive behavior data from \\citet{anderson2010violent}. Posterior standard deviations are reported between brackets.}",
    "\\begin{center}%",
    "\\begin{tabular}{lcccccccccc}",
    "\\multicolumn{11}{c}{\\bf All Experiments} \\tabularnewline",
    one_table(tables_anderson[[1]]),
    "\\tabularnewline",
    "\\multicolumn{11}{c}{\\bf Only Best Practice Experiments} \\tabularnewline",
    one_table(tables_anderson[[2]]),
    "\\tabularnewline",
    "\\multicolumn{11}{c}{\\bf Without Best Practice Experiments} \\tabularnewline",
    one_table(tables_anderson[[3]]),
    "\\end{tabular}",
    "\\end{center}",
    "\\end{table}")

writeLines(anderson_table, "tables/anderson2010.tex")

cuddy_table = 
  c("%% This document is generated by R: DO NOT EDIT BY HAND!",
    "\\begin{table}",
    "\\caption{\\label{tab:cuddy2018} Power posing example: Posterior means for LOOICs and parameters (mean effect $\\theta$, standard deviation $\\tau$, probabilities of \\emph{p}-hacking $\\pi$/probabilities of being published $\\rho$) of the \\emph{p}-hacking, publication bias, and classical meta-analysis (uncorrected) model estimated on the data by \\citet{cuddy2018p}. The results in the top table are obtained with all studies, those in the bottom without the outlier $x_{12}$. Posterior standard deviations are reported between brackets.}",
    "\\noindent",
    "\\begin{center}%",
    "\\begin{tabular}{lrrrrrrrrr}",
    "\\multicolumn{10}{c}{\\bf All studies}\\\\",
    one_table(tables_cuddy[[1]]),
    "\\tabularnewline",
    "\\multicolumn{10}{c}{\\bf Without outlier}\\\\",
    one_table(tables_cuddy[[2]]),
    "\\end{tabular}",
    "\\end{center}",
    "\\end{table}")

writeLines(cuddy_table, "tables/cuddy2018.tex")
